=== BFranky37/DeliveryApp/src/main/resources/xsd/discounts.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="discounts">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="discount" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="rate" type="xs:double"/>
                        </xs:sequence>
                        <xs:attribute type="xs:byte" name="id" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== BFranky37/DeliveryApp/src/main/resources/discounts.xml
<?xml version="1.0" encoding="UTF-8"?>

<discounts>
xsi:schemaLocation="https://www.w3schools.com/xml discounts.xsd">
    <discount>
        <name>Veteran</name>
        <rate>.10</rate>
    </discount>
    <discount>
        <name>Senior Citizen</name>
        <rate>.05</rate>
    </discount>
    <discount>
        <name>Employee</name>
        <rate>.10</rate>
    </discount>
    <discount>
        <name>Membership Holder</name>
        <rate>.15</rate>
    </discount>
</discounts>
