=== BFranky37/DeliveryApp/src/main/resources/insurance.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="insurances">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="insurance">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="base_cost" type="xs:double"/>
                            <xs:element name="price_rate" type="xs:double"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== BFranky37/DeliveryApp/src/main/resources/insurance.xml
<?xml version="1.0" encoding="UTF-8"?>

<insurances>
    xsi:schemaLocation="https://www.w3schools.com/xml insurance.xsd">
    <insurance>
        <name>Basic Insurance</name>
        <base_cost>.3</base_cost>
        <price_rate>.015</price_rate>
    </insurance>
    <insurance>
        <name>Fragility Insurance</name>
        <base_cost>.5</base_cost>
        <price_rate>.03</price_rate>
    </insurance>
    <insurance>
        <name>High Value Insurance</name>
        <base_cost>1</base_cost>
        <price_rate>.5</price_rate>
    </insurance>
    <insurance>
        <name>High Value Fragility Insurance</name>
        <base_cost>1.5</base_cost>
        <price_rate>.55</price_rate>
    </insurance>
</insurances>
